# Generated by Django 3.0.5 on 2020-04-15 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cover', models.ImageField(height_field=50, upload_to='images/', width_field=100)),
                ('size', models.BinaryField(max_length=10)),
            ],
        ),
    ]
