# Generated by Django 3.0.5 on 2020-04-15 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webimage',
            name='cover',
            field=models.ImageField(height_field=129, upload_to='images/', width_field=100),
        ),
        migrations.AlterField(
            model_name='webimage',
            name='size',
            field=models.BinaryField(max_length=6000),
        ),
    ]
