# Generated by Django 3.0.5 on 2020-04-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_auto_20200415_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(height_field=129, max_length=10000, upload_to='images/', width_field=100),
        ),
    ]
