# Generated by Django 3.0.5 on 2020-04-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_remove_post_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.AddField(
            model_name='post',
            name='name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(height_field='url_height', max_length=10000, upload_to='images/', width_field='url_width'),
        ),
    ]
