# Generated by Django 3.0.5 on 2020-04-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0007_auto_20200415_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='image_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(height_field='image_height', max_length=10000, upload_to='images/', width_field='image_width'),
        ),
    ]
