# Generated by Django 3.0.5 on 2020-04-16 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0008_auto_20200415_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='size',
            field=models.BinaryField(default=0, max_length=6000),
            preserve_default=False,
        ),
    ]
