# Generated by Django 3.0.5 on 2020-04-16 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0012_auto_20200416_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='size',
        ),
    ]
