# Generated by Django 3.0.5 on 2020-04-16 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0014_auto_20200416_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(height_field='image_height', max_length=1000, upload_to='media/images/', width_field='image_width'),
        ),
    ]
